name = "baitless-news-worker"
main = "worker/src/index.ts"
compatibility_date = "2024-04-02"

[build]
command = "npm install --prefix worker"

[vars]
# OPENAI_API_KEY = "your-openai-key"
# NEWS_API_KEY = "your-newsorg-key"
